### ISSUE TITLE
Executable name hides /sbin/ip

### ISSUE THREAD

**Issue by maxdevjs** [bntzio/cliip#1]
This package is awesomely handy, :heart: it.

The only hitch I found is that it hides *nix's `/sbin/ip`.

**Comment by bntzio** [comment]
@max-devjs on linux yeah, there's already a command called `ip` but not in mac, a workaround is to change the ip command in the `package.json` to something else (like `cliip`).

And then use `cliip` instead of `ip`.

**Comment by maxdevjs** [comment]
Yes, it is a fair solution. I was just wondering if it could be done as a standardized solution at the source (in the package): `ip` is a pretty common term in aliases, script, etc...

Again, nice work!

**Comment by bntzio** [comment]
yeah that's a good idea, `cliip` instead of `ip`, will release the change later.

Thanks! 😄

**Comment by bntzio** [comment]
@max-devjs see v2.0.0 release 👉 https://github.com/bntzio/cliip/releases/tag/v2.0.0 😄

**Comment by maxdevjs** [comment]
:smile:

![cliip](https://cloud.githubusercontent.com/assets/22229196/26042210/da4db20e-3909-11e7-9899-1ec392caca9b.png)

**Comment by bntzio** [comment]
2.0.0 coz to use `cliip` it now needs to be called with `cliip` instead of `ip` 🙂

**Comment by maxdevjs** [comment]
Yes, I was just visually celebrating :champagne:
