### ISSUE TITLE
hostname: No Hostname

### ISSUE THREAD

**Issue by maxdevjs** [bntzio/cliip#2]
Some times I get a laconic `hostname: No Hostname`. 

It happens two or three times in a row, then I get the right hostname two or three times in a row, then again No Hostname and so on. Any idea?

**Comment by bntzio** [comment]
@max-devjs that's coming from the [ipinfo](http://ipinfo.io) API. Closing issue ✅.

**Comment by maxdevjs** [comment]
@bntzio, curious: `that's coming` meaning that is an API behavior?

**Comment by bntzio** [comment]
@max-devjs yeah nothing to do with cliip itself 😄

**Comment by maxdevjs** [comment]
Thank you
